apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-conf
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
data:
  shared.yaml: |-
{{- toYaml .Values.global.shared_conf | nindent 4 }}
