REMOTE_URL:
- file:///opt/spaceone/notification/config/database.yaml
- file:///opt/spaceone/notification/config/shared.yaml
- file:///opt/spaceone/notification/config/application.yaml
GLOBAL:
  MAX_WORKERS: 1000
  DATABASES:
    default:
      db: notification
      host: mongodb
      port: 27017
      maxPoolSize: 200
      username: notification_user
      password: notification_password
  CACHES:
    default:
      backend: spaceone.core.cache.redis_cache.RedisCache
      host: redis
      port: 6379
      db: 1
      encoding: utf-8
      socket_timeout: 10
      socket_connect_timeout: 10
  LOG:
    loggers:
      spaceone:
        handlers:
          - console
          - file
    handlers:
      file:
        type: file
        filename: /var/log/spaceone/notification.log
  HANDLERS:
    authentication:
    - backend: spaceone.core.handler.authentication_handler.AuthenticationGRPCHandler
      uri: grpc://notification:50051/v1/Domain/get_public_key
    authorization:
    - backend: spaceone.core.handler.authorization_handler.AuthorizationGRPCHandler
      uri: grpc://notification:50051/v1/Authorization/verify
  CONNECTORS:
    IdentityConnector:
      endpoint:
        v1: grpc://identity:50051
    SecretConnector:
      endpoint:
        v1: grpc://secret:50051
    PluginConnector:
      endpoint:
        v1: grpc://plugin:50051
    RepositoryConnector:
      endpoint:
        v1: grpc://repository:50051
  QUEUES:
    notification_q:
      backend: spaceone.core.queue.redis_queue.RedisQueue
      host: redis
      port: 6379
      channel: notification_job