###############################
# DEFAULT 
###############################
enabled: true
developer: false
grpc: true
scheduler: false
worker: false
rest: false
name: identity
image:
    name: spaceone/identity
    version: latest
imagePullPolicy: IfNotPresent

resources: {}
#     grpc: 
#         requests:
#             memory: "128Mi"
#             cpu: "25m"
#         limits:
#             memory: "256Mi"
#             cpu: "50m"
#     rest: 
#         requests:
#             memory: "128Mi"
#             cpu: "25m"
#         limits:
#             memory: "256Mi"
#             cpu: "50m"
#     scheduler: 
#         requests:
#             memory: "128Mi"
#             cpu: "25m"
#         limits:
#             memory: "256Mi"
#             cpu: "50m"
#     worker: 
#         requests:
#             memory: "128Mi"
#             cpu: "25m"
#         limits:
#             memory: "256Mi"
#             cpu: "50m"

database: {}

###########################################################
# if you want to use API key or spacectl
# Put full FQDN at endpoint
# Ex) endpoint: grpc+ssl://identity.example.com:443/v1
# grpc+ssl is for gRPC ALB ingress controller
# If you want to use NLB instead of ALB, 
# You have to use grpc://identity.example.com:50051/v1
###########################################################
application_grpc:
    ENDPOINTS:
    - service: identity
      name: Identity Service
      endpoint: grpc+ssl://identity:443/v1
    - service: inventory
      name: Inventory Service
      endpoint: grpc+ssl://inventory:443/v1
    - service: plugin
      name: Plugin Manager
      endpoint: grpc+ssl://plugin:443/v1
    - service: repository
      name: Repository Service
      endpoint: grpc+ssl://repository:443/v1
    - service: secret
      name: Secret Manager
      endpoint: grpc+ssl://secret:443/v1
    - service: monitoring
      name: Monitoring Service
      endpoint: grpc+ssl://monitoring:443/v1
    - service: config
      name: Config Service
      endpoint: grpc+ssl://config:443/v1
    - service: power_scheduler
      name: Power Scheduler Service
      endpoint: grpc+ssl://power-scheduler:443/v1
    - service: statistics
      name: Statistics Service
      endpoint: grpc+ssl://statistics:443/v1
    - service: billing
      name: Billing Service
      endpoint: grpc+ssl://billing:443/v1
    - service: notification
      name: Notification Service
      endpoint: grpc+ssl://notification:443/v1
    LOG:
        filters:
            exclude:
                rules:
                  tnx_method:
                  - Domain.get_public_key
                  - Authorization.verify

application_rest: {}

##########################
# local sidecar
##########################
sidecar:
    rest_web:
        image:
            name: nginx
            version: stable
            imagePullPolicy: IfNotPresent
        resources: {}
        #     requests:
        #         memory: "128Mi"
        #         cpu: "25m"
        #     limits:
        #         memory: "256Mi"
        #         cpu: "50m"
    grpc: {} 
    rest: {}
    scheduler: {}
    worker: {}

##########################
# Local volumes
##########################
volumes:
    - name: timezone
      hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
    - name: log-volume
      emptyDir: {}
#######################
# global variable
#######################
global:
    shared: {}
    backend:
        sidecar: []
    #        - name: mongos
    #          image: mongo:4.4.0-bionic
    #          command: [ 'mongos', '--config', '/mnt/mongos.yml', '--bind_ip_all' ]
    #          volumeMounts:
    #            - name: mongos-conf
    #              mountPath: /mnt/mongos.yml
    #              subPath: mongos.yml
    #              readOnly: true
    #            - name: mongo-shard-key
    #              mountPath: /opt/mongos/mongo-shard.pem
    #              subPath: mongo-shard.pem
    #              readOnly: true
    #
        volumes: []
    #        - name: mongo-shard-key
    #          secret:
    #              defaultMode: 0400
    #              secretName: mongo-shard-key
    #        - name: mongos-conf
    #          configMap:
    #              name: mongos-conf
    #        - name: shared-conf
    #          configMap:
    #              name: shared-conf

# Service
service:
    grpc:
        type: ClusterIP
        annotations:
            nil: nil
        ports:
            - name: grpc
              port: 50051
              targetPort: 50051
              protocol: TCP

################################
# volumeMount per deployment
################################
volumeMounts:
    application_grpc: []
    application_rest: []
    application_scheduler: []
    application_worker: []


####################################
# pod spec (append more pod spec)
# example nodeSelect
#
# pod:
#   spec:
#     nodeSelector:
#       application: my-node-group
####################################
pod:
    spec: {}
