{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "spaceone.labels" . | indent 4 }}
    spaceone.service: mongodb
  name: mongodb 
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      spaceone.service: mongodb
  template:
    metadata:
      annotations:
        spaceone.deployment.tool: helm
      labels:
        spaceone.service: mongodb
        app.kubernetes.io/name: mongodb
    spec:
      terminationGracePeriodSeconds: {{ .Values.gracePeriod }}
{{- if .Values.imagePullSecrets}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end}}
      containers:
        - name: mongodb
          image: {{ .Values.image.name }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
{{- if .Values.resources }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
{{- end }}
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            - name: mongodb-user-conf
              mountPath: /docker-entrypoint-initdb.d/user.js
              subPath: user.js
              readOnly: true
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.username }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.password }}
            - name: MONGO_INITDB_DATABASE
              value: admin
{{- if .Values.global.common_env }}
{{- toYaml .Values.global.common_env | nindent 12 }}
{{- end }}

      volumes:
{{ if .Values.pvc.storageClassName }}
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: {{ .Release.Namespace }}-mongodb-pvc
{{ else }}
        - name: mongodb-data
          emptyDir: {}
{{- end }}
        - name: mongodb-user-conf
          configMap:
            name: mongodb-user-conf

{{- end }}
