{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-user-conf
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
data:
  user.js: |-
{{ .Files.Get "config/user.js" | nindent 4 }}
{{- end }}

