REMOTE_URL:
- file:///opt/spaceone/console-api-v2/config/shared.yaml
- file:///opt/spaceone/console-api-v2/config/application.yaml
GLOBAL:
  MAX_WORKERS: 1000
  CACHES:
    default:
      backend: spaceone.core.cache.redis_cache.RedisCache
      host: redis
      port: 6379
      db: 1
      encoding: utf-8
      socket_timeout: 10
      socket_connect_timeout: 10
  LOG:
    loggers:
      spaceone:
        handlers:
          - console
          - file
    handlers:
      file:
        type: file
        filename: /var/log/spaceone/console-api-v2.log
  HANDLERS:
    authentication:
    - backend: spaceone.core.handler.authentication_handler.AuthenticationGRPCHandler
      uri: grpc://identity:50051/v1/Domain/get_public_key